### PR TITLE
Feature/railties 7

### PR DESCRIPTION
**Pull request by tagliala**
# ⚠️ DO NOT RELY ON THIS BRANCH FOR DEPLOYMENT ⚠️

### CODE REVIEW

**Comment by Startouf** [comment]
Hi there @tagliala ! 
We just wanted to notify you that we're using your PR to use active admin with rails 7. 
If you make force pushes, it'll mess up on our side, but I guess this is okay since this is some sorte of edge development. We're watching this PR on our side to get notifications and update the bundle when needed. 

Do you have any plans/schedule to work on the failing tests to hopefully get this merged into active admin main repo ?

**Comment by tagliala** [comment]
> If you make force pushes, it'll mess up on our side

Sorry to hear that, but please make a fork and do not rely on this PR for deployed applications, it is highly experimental and I will push force when needed

> Do you have any plans/schedule to work on the failing tests to hopefully get this merged into active admin main repo ?

Please take a look at activeadmin/activeadmin#7235, there are some blocking dependencies upstream and a known issue with autoload that I do not know how to fix

**Comment by sachin-amzur** [comment]
@tagliala I am getting this issue with this branch, how to fix it?

Screenshot from 2022-02-20 10-48-35

**Comment by tagliala** [comment]
just run `bundle update activeadmin` again. I'm force-pushing to this branch, so the old reference is not available anymore

Please also do not rely on this branch for deployments

**Comment by sachin-amzur** [comment]
> just run `bundle update activeadmin` again. I'm force-pushing to this branch, so the old reference is not available anymore
> 
> Please also do not rely on this branch for deployments

@tagliala then what is the solution to use activeadmin with rails 7? Please suggest.

**Comment by tagliala** [comment]
@sachin-amzur you can fork this repo and point to a branch you have control on

**Pull request closed without merging**
